project_id = "ahnxmwixvbfgevujxhgi"

[functions.refresh-prices]
verify_jwt = false

[functions.take-snapshot]
verify_jwt = false

[functions.enrich-securities]
verify_jwt = true

[functions.execute-dca]
verify_jwt = false
