project_id = "ahnxmwixvbfgevujxhgi"

[functions.refresh-prices]
verify_jwt = true

[functions.take-snapshot]
verify_jwt = true

[functions.scheduled-snapshots]
verify_jwt = false

[functions.enrich-securities]
verify_jwt = true

[functions.refresh-snapshot-metadata]
verify_jwt = true

[functions.execute-dca]
verify_jwt = false

[functions.bridge-proxy]
verify_jwt = true

[functions.resolve-isin]
verify_jwt = false
